config: DS_COMPONENT_ALSA_UCM_CONF
tasks:
- cmd: install.sh
  cmd_type: target
  description: Installing and alsa ucm config files
- cmd: packages.sh
  cmd_type: packagelist
  description: Adding package dependencies for alsa-ucm-conf

